apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus-deployment
  name: prometheus
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.20.0
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=24h"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
        - name: prometheus-rules
          mountPath: /etc/config/rules
        - name: localtime
          mountPath: /etc/localtime
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      securityContext:
        runAsUser: 0
      serviceAccountName: prometheus    
      volumes:
      - name: data
        hostPath:
          path: /var/lib/docker/prometheus 
      - name: config-volume
        configMap:
          name: prometheus-config   
      - name: prometheus-rules
        configMap:
          name: prometheus-rules        
      - name: localtime
        hostPath:
          path: /etc/localtime
